nodeLinker: node-modules

packageExtensions:
  'auto@*':
    peerDependencies:
      '@types/node': '*'
      'typescript': '*'
  '@auto-it/npm@*':
    peerDependencies:
      '@types/node': '*'
      'typescript': '*'
  '@auto-it/released@*':
    peerDependencies:
      '@types/node': '*'
      'typescript': '*'
  '@auto-it/version-file@*':
    peerDependencies:
      '@types/node': '*'
      'typescript': '*'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependencies:
      'typescript': '*'
  '@typescript-eslint/utils@*':
    peerDependencies:
      'typescript': '*'
